USE [IncompatibleFoodApi]
GO
/****** Object:  Table [dbo].[Tbl_IncompatibleFood]    Script Date: 12/20/2025 5:14:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tbl_IncompatibleFood](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FoodA] [nvarchar](50) NOT NULL,
	[FoodB] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Tbl_IncompatibleFood] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Tbl_IncompatibleFood] ON 

INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (1, N'ဆူးပုတ်ရွက် ', N'ဆိတ်သား ', N'မူးဝေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (2, N'ကိုကိုး(ဖျော်ရည်)', N'ပဲမြစ် ', N'မူးဝေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (3, N'ဝက်သား', N'ဒေါင်းသား ', N'ဝမ်းလျှော ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (4, N'ဝက်သား ', N'ပေရည်ပေသီး ', N'ဝမ်းလျှော ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (5, N'ရှောက်သီး ', N'စောင်းလျှားသီး ', N'ဝမ်းလျှော ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (6, N'ခိုသား ', N'စောင်းလျားသီး ', N'ဝမ်းလျှော ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (7, N'ဆီးသီး', N'စားတော်ပဲ ', N'ဝမ်းလျှော ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (8, N'ဘဲဥ', N'ဗျိုင်းသား ', N'ဝမ်းလျှော ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (9, N'ကျွဲသား ', N'ကြာရိုးကြာစွယ် ', N'ဝမ်းလျှော ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (10, N'ကြက်သား ', N'ကြက်ဟင်းခါးသီး ', N'အော့အန် ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (11, N'အာလူး', N'ကြက်ဟင်းခါးသီး ', N'အော့အန် ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (12, N'စိမ်းစားဥ ', N'ရှောက်သီး ', N'အော့အန် ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (13, N'ဘဲဥ ', N'ဖရဲသီး ', N'အော့အန် ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (14, N'သံပုရာသီး', N'ပဲတကော ', N'အော့အန် ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (15, N'ပျားရည် ', N'ပိန္နဲသီး ', N'အော့အန် ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (16, N'စိမ်းစားဥ ', N'ချိုချဉ် ', N'အော့အန် ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (17, N'လက်ဖက်သုပ် ', N'မယ်ဇလီရွက် ', N'အော့အန် ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (18, N'နို့အေးချောင်း ', N'သခွါးသီး ', N'ရင်ကျပ် ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (19, N'နို့အေးချောင်း ', N'စိမ်းစားဥ ', N'ရင်ကျပ် ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (20, N'ကြက်သား ', N'ကြောင်လျှာသီး ', N'အကြောတက်')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (21, N'ကြက်ဟင်းခါးသီး ', N'မှို ', N'အကြောတက် ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (22, N'ကြက်ဥ ', N'တမာရွက် ', N'အကြောတက် ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (23, N'ကင်းပုံရွက် ', N'နှမ်း ', N'အကြောတက် ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (24, N'ရွှေဖရုံသီး', N'ပုစွန် ', N'ဝမ်းကိုက်နာ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (25, N'ခိုသား ', N'ငုံးသား ', N'ရင်ပူ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (26, N'ဒူးရင်းသီး ', N'အရက် ', N'ရင်ပူ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (27, N'ကဏန်း ', N'ခရမ်းသီး ', N'အဆိပ်သင့် ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (28, N'နွားနို့ ', N'ငါးအစိမ်း ', N'အဆိပ်သင့် ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (29, N'အမဲသား', N'တရုတ်ကြက်သွန်မိတ် ', N'အဆိပ်သင့် ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (30, N'မင်းကွတ်သီး ', N'သကြား ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (31, N'ရေခဲမုန့် ', N'ဂျင်းသုပ် ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (32, N'လက်ဖက်သုပ် ', N'ကျွဲခေါင်းသီး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (33, N'သံပုရာသီး ', N'ကျွဲခေါင်းသီး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (34, N'ဖရုံသီး ', N'ခိုသား ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (35, N'ကြောင်လျှာသီး ', N'ငါးသေတ္တာ ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (36, N'ကြောင်လျှာသီး', N'ပဲဒလက် ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (37, N'ကြောင်လျှာသီး ', N'စပါးကြီးမြွေ ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (38, N'ချင်း(ဂျင်း)', N'သင်္ဘောသီး', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (39, N'ချင်း(ဂျင်း) ', N'ခိုသား ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (40, N'ထန်းလျက် ', N'နလင်ကျော် ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (41, N'ထန်းလျက် ', N'(၂၇)ပါးဆေး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (42, N'ထန်းလျက် ', N'သပြေသီး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (43, N'ဂွေးသီး ', N'အာတာလွတ်ဥ ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (44, N'ဂွေးသီး ', N'နို့အေးချောင်း ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (45, N'ပီလောပီနှံ ', N'မျှစ်ချဉ်', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (46, N'ပီလောပီနှံ ', N'ပဲကြားလှော် ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (47, N'ပီလောပီနှံ ', N'ဒေါင်းသား ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (48, N'ကြက်ဆူသီး ', N'ငှက်သား ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (49, N'ကျေးသား ', N'ဘူးသီး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (50, N'ဝက်သား ', N'ဗျိူင်းသား ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (51, N'ဝက်သား ', N'ထန်းရည်ချို ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (52, N'ဝက်သား ', N'ကြာရိုးကြာစွယ် ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (53, N'ကျွဲသား ', N'ဆိတ်သား ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (54, N'နို့ဆီ', N'ကိုးပါးဆေးလျက်ဆား ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (55, N'မိုင်လို(အမှုန့်)', N'ပဲမြစ် ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (56, N'ကြံ့သား ', N'ငါးအမျိုးမျိုး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (57, N'ချောကလက် ', N'ပဲမြစ် ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (58, N'ချောကလက် ', N'စောင်းလျားသီး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (59, N'သိုးသား ', N'စောင်းလျားသီး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (60, N'တညင်းသီး ', N'ရှိုန်းခို ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (61, N'တညင်းသီး ', N'ဒူးရင်းသီး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (62, N'တညင်းသီး ', N'မှို ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (63, N'နွားနို့ ', N'မှို ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (64, N'ဖားသား ', N'မှို ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (65, N'ပျားရည် ', N'အုန်းသီး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (66, N'ပျားရည် ', N'သြဇာသီး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (67, N'ပျားရည် ', N'ဥသျှစ်သီး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (68, N'နွားနို့ ', N'သံပုရာသီး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (69, N'လယ်ကဏန်း ', N'မှို ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (70, N'ကျွဲကောသီး ', N'သံပုရာသီး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (71, N'ထန်းသီး/ ရည် ', N'ငှက်ပျောသီး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (72, N'ကိုင်းဥ ', N'ပုစွန်ချဉ် ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (73, N'အမဲသား ', N'ခရု ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (74, N'ယုန်သား ', N'မှို ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (75, N'ရေခဲမုန့် ', N'ချင်းသုပ် ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (76, N'အုန်းနို့ခေါက်ဆွဲ ', N'ပက်စီ ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (77, N'နွားနို့ ', N'အချဉ်အမျိုးအမျိုး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (78, N'ကျွှဲခေါင်းသီး ', N'သံပုရာသီး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (79, N'ပီလောပီနံ ', N'အချဉ်အမျိုးမျိူး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (80, N'ရှောက်သီး ', N'နွားနို့၊ နို့ရည်', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (81, N'ပျားရည် ', N'ရှားစောင်း ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (82, N'လက်ဖက်ပုပ် ', N'မဲဇလီအဖူး/အရွက် ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (83, N'စောင်းလျား ', N'ရှောက် ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (84, N'မတ်ပဲ', N'မုန်လာဥ ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (85, N'ခံသီး ', N'ငရုတ်ကောင်း ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (86, N'သံပရာ ', N'ပတဲကော ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (87, N'ကင်းပိန့်ရွက် ', N'နှမ်းပတ်နှင်းမုန့် ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (88, N'အင်ဥ ', N'ဝါးမျှစ် ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (89, N'ဝါစေ့ဆီ ', N'ဝက်သား ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (90, N'ပဲဒလက်စေ့ ', N'ဆိတ်သား ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (91, N'နနွင်း ', N'မိကျောင်းသား ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (92, N'ကကတစ် ', N'ကြာဟင်းရွက် ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (93, N'သခွားသီး ', N'ရေခဲချောင်း ', N'ရင်ကျပ် ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (94, N'စိမ်းစာဥ', N'ရေခဲချောင်း ', N'ရင်ကျပ် ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (95, N'ချိုချဉ်', N'ပဲငါးပိ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (96, N'ခြေလေးချောင်းမျိုး', N'ခရုသား', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (97, N'ခြင်ဆီ', N'ထောပတ်', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (98, N'ကလောဥ', N'ဒန့်သလွန်', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (99, N'ကလောဥ', N'ဇီးဖြူသီး', N'သေ ')
GO
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (100, N'ကလောဥ', N'လက်လုပ်ချဉ်များ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (101, N'ကြက်ဆူဆီ ', N'ခါသား ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (102, N'ကြက်ဆူဆီ ', N'ငှက်သား ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (103, N'ကြက်ဆူဆီ ', N'ဖွတ်သား ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (104, N'ကြက်ဆူဆီ ', N'ဒေါင်းသား ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (105, N'ကြက်ဆူဆီ ', N'ဥမျိုးစုံ ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (106, N'ကြက်သား ', N'နို့ချဉ်အမျိုးမျိုး ', N'?? ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (107, N'ကြက်သား ', N'အင်ဖူး ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (108, N'ကြက်သွန်ဖြူ ', N'နို့ရည်၊ ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (109, N'ကြက်သွန်ဖြူ ', N'ပျားရည် ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (110, N'ကြက်ဥ', N'ပုဇွန်ချဉ်', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (111, N'ကြက်ဥ', N'အမ်ပီဆေးပြား', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (112, N'ကြက်ဥ', N'ခံသီး', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (113, N'ကြေးခွက်', N'အချဉ်သီး', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (114, N'ကျွဲနို့', N'ကြာစွယ်', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (115, N'ကျွဲနို့', N'ဖရုံသီး', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (116, N'ကျောက်ဖရုံ', N'အိုးမဲ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (117, N'ကောက်ညှင်း', N'ရေငန်းသီး', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (118, N'ကိုင်းဥ', N'ပုဇွန်ချဉ်', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (119, N'ကုလားပဲ', N'နွားနို့', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (120, N'ကုလားပဲ', N'နို့ချဉ်၊ နို့ရည်', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (121, N'ကျေးသား', N'ကြက်ဆူဆီ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (122, N'ကုန်းငှက်သား', N'ကြက်ဆူဆီ', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (123, N'ကန့်ချူပ်နီ', N'သေရည်', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (124, N'ကန်စွန်းဖြစ်', N'နှမ်းမှုန့်', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (125, N'ဂင်ပိတ်ရွက်', N'ပျားရည်', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (126, N'ဂင်ပိတ်ရွက်', N'ဥသျှစ်သီး', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (127, N'ဂင်ပိတ်ရွက်', N'နှမ်းဆီ ၊ နှမ်းဖတ်ချဉ်', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (128, N'ကတိုး', N'သရက်သီး', N'သေ ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (129, N'ချောကလက်', N'မြေပဲ', N'တောက်')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (130, N'ကြောင်လျှာသီး', N'ထန်းလျက်ချို', N'ဝမ်းလျှော')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (131, N'ဝက်သား', N'နို့ချဉ်', N'ဝမ်းလျှော')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (132, N'ဝက်သား', N'ကျွဲနို့', N'ဝမ်းလျှော')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (133, N'သစ်ကြာသီး', N'မြေဇာဥ', N'အော့အန်')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (134, N'စိမ်းစားဥ', N'ခိုသား', N'အော့အန်')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (135, N'အင်သမင်နွယ်', N'ပျားရည်', N'အော့အန်')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (136, N'ပဲငပိ', N'ချိုချဉ်', N'အော့အန်')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (137, N'လက်ဖက်သုတ်', N'မဲဇလီဖူးရွက်', N'အော့အန်')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (138, N'သမင်သား', N'ဝါဆီ', N'ရင်ကြပ်')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (139, N'မျှစ်', N'အင်ဥ', N'သေ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (140, N'တစောင်းဆူး', N'မျှစ်', N'ရင်ပူ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (141, N'ပဲမုန့်', N'မုန်လာမြစ်', N'မူးဝေ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (142, N'ဆူးပုပ်ရွက်', N'ဆိတ်နို့၊ ဆိတ်သား', N'မူးဝေ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (143, N'ငါးသေတ္တာ', N'ထိကရုံး', N'မူးဝေ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (144, N'နို့ဆီ', N'၂၇ ပါးဆေး', N'သေ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (145, N'ထန်းလျက်', N'ဘာမီတွန်', N'သေ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (146, N'ငါးရံ့သား', N'ပွေးသား', N'သေ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (147, N'နို့အေးချောင်း', N'ပွေးသား', N'သေ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (148, N'စိန် ၊ Nဘတ်စပရို', N'သံပရာသီး', N'သေ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (149, N'ခရမ်းပိန်း', N'နို့ရည်', N'သေ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (150, N'သေရည်အရက်', N'ဉာဏ်ရွက်', N'သေ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (151, N'သေရည်အရက်', N'အေပီစီဆေးပြား', N'သေ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (152, N'ဒူးရင်းသီး', N'ရှိန်းခို', N'သေ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (153, N'ရေငန်သီး', N'ကောက်ညှင်း', N'??')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (154, N'ဂျယ်လီ', N'ကော်ဖီမစ်', N'သေ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (155, N'ပီလောပီနံဥ', N'ပဲကြားလှော်', N'သေ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (156, N'ပီလောပီနံဥ', N'မျှစ်ချဉ်', N'သေ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (157, N'ဆိုဒါ', N'၉ ပါးဆေး', N'သေ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (158, N'ဘာမီတွန်', N'တစ်ဖီ (အစိမ်းကဒ်)', N'သေ')
INSERT [dbo].[Tbl_IncompatibleFood] ([Id], [FoodA], [FoodB], [Description]) VALUES (159, N'test', N'string', N'string')
SET IDENTITY_INSERT [dbo].[Tbl_IncompatibleFood] OFF
GO
