@BurmaCalendar.Api_HostAddress = http://localhost:5000

### Get Calendar Month List (Page 1, Size 5)
GET {{BurmaCalendar.Api_HostAddress}}/api/BurmaCalendar/1/5
Accept: application/json

### Get Calendar Month by ID (1)
GET {{BurmaCalendar.Api_HostAddress}}/api/BurmaCalendar/1
Accept: application/json

### Try to Create a Month (Expected: 405 Method Not Allowed)
POST {{BurmaCalendar.Api_HostAddress}}/api/BurmaCalendar
Content-Type: application/json

{
  "monthMm": "စမ်းသပ်",
  "monthEn": "Test"
}
